### ISSUE TITLE
"Choose Popup" not working?

### ISSUE THREAD

**Issue by dedablio** [bashari10/elementor-popup#8]
Hi there.
Really great you're doing this plugin.

I'm trying to use it, but the "Choose Popup" option is empty. 
I don't know if it's supposed to have anything there or I'm not figuring out the way to use it

Any info is much appreciated
Regards

**Comment by BuiltByLou** [comment]
Hi,
You should have a new sub menu on your left menu that's called PopUps.

Click there, create a new popup.

Go back to the page where you want to use it and it should be there for you
to choose :)


Em 13/04/2017 22:18, "dedablio" <notifications@github.com> escreveu:

**Comment by dedablio** [comment]
thanks for your help, but I can't find this new  sub menu

All that I have is the popup option in the widget menu. 
I drag it to the page and what I get is this:
![elementor-popup](https://cloud.githubusercontent.com/assets/23621610/25025502/edc32b10-2078-11e7-9551-d325ee9d9d64.png)

**Comment by BuiltByLou** [comment]
The sub menu is on WordPress dashboard. Where you choose post, page, multimedia, etc etc 

![img_20170413_225036](https://cloud.githubusercontent.com/assets/7611772/25025851/d48a199c-209b-11e7-85f5-ab385468b02f.jpg)

**Comment by badcat** [comment]
Once you make the popup and add it a page - how do you get the popup content to show? I only see the title of the popup after clicking the popup's button

**Comment by dedablio** [comment]
Thank you very much
It's working !

I wasn't understanding it was on the WordPress menu.
Just to add a info to others, you have to publish the popup page before be able to use it.

Thanks again, great widget

**Comment by dedablio** [comment]
Badcat,

you create a popup page (from the wordpress menu - popups), edit it with elementor and add the content you like.
After it you edit a page and add the popup widget. It will add a button and you can choose one of the popup pages you created before.

**Comment by BuiltByLou** [comment]
You probably don't add content to the pop-up, and have a withe page.

It's a 2 steps process, 1st you go to the sub menu popup, create a new one
and edit him with elementor ( if you don't can't use elementor here you
first need to go to elementor options and enable it to show on PopUps)

Then after you had the pop-up created and added the content you want you go
to the page where you want to use it, and select the pop-up you just
created.

This way when you click on the button you should see the pop-up.

Em 13/04/2017 22:56, "BadCat Design" <notifications@github.com> escreveu:

**Comment by badcat** [comment]
@dedablio I understand the process.  The issue that the popup content doesn't show up.  Only the title shows.

![screen shot 2017-04-13 at 6 05 16 pm](https://cloud.githubusercontent.com/assets/26096/25026279/cb2dd910-2073-11e7-853e-3391af5713dc.png)

Perhaps some issue here...

`<?php
$frontend = new Frontend;
echo $frontend->get_builder_content($selectedPopup->post->ID, true);
?>
`

**Comment by dedablio** [comment]
bad cat, did you add content to de popup page?

**Comment by badcat** [comment]
@dedablio 
Of course :) 

Please show me an example of the popups working on a live site.

I also noticed - the options set in the Elementor side panel such as "Button Type: Danger" do not work.

**Comment by BuiltByLou** [comment]
Hmm I'm using the last version and it is working for me.

When did you install the plugin?

Em 13/04/2017 23:07, "BadCat Design" <notifications@github.com> escreveu:

**Comment by badcat** [comment]
@Luisfmarkes It's a fresh install from GitHub.  Version 0.3.0

**Comment by dedablio** [comment]
It works fine for me.
Even the  "Button Type: Danger" 
Same version as yours, re-installed today

**Comment by badcat** [comment]
Please let me see this working on a live site

**Comment by dedablio** [comment]
just a test:
http://www.geraflex.com.br/lp/teste-pro/

**Comment by badcat** [comment]
@dedablio thank you for the link.  

So very strange.  Running current WP 4.7.3, only Elementor 1.4.2 and Popups 0.3.0 with the twentyseventeen theme and it's not working.

**Comment by badcat** [comment]
AH HAH!!

The Popup must also be built with Elementor.  Creating a Popup with _only_ the Standard WordPress editor causes the content to not show.

Problem solved - hope this helps someone.

**Comment by badcat** [comment]
@bashari10 

I still think this line below should be altered to use standard WordPress content.

`<?php $frontend = new Frontend; echo $frontend->get_builder_content($selectedPopup->post->ID, true); ?>`

so instead of relying on **"get_builder_content"**, we can also use **"get_the_content"**.

**Comment by bashari10** [comment]
I can't rely on get_the_content, if I do, a few Elementor widgets will not work in popups. Another reason to use get_builder_content is that Elementor enqueue special css file with all the styles of the popup's widget (like width, height, font sizes, etc.). This will not happen with get_the_content.
